#pragma once
#define TXT_PileType							"桩类型："
#define	TXT_PileType_Solid						"实心桩或桩端封闭"
#define TXT_PileType_SteelAndConcrete			"钢管桩与预制混凝土管桩"
#define	TXT_PileCrossSectionType				"桩截面类型："
#define TXT_PileCrossSectionType_Square			"方型截面"
#define TXT_PileCrossSectionType_Annular		"环形截面"
#define TXT_PileCrossSectionType_SquareWithHole	"方形空心截面"
#define TXT_PileCrossSectionType_Polygon		"多边形截面"
#define TXT_PileCode							"桩轴网坐标(横-纵)："
#define TXT_PileSideLength						"桩边长(m)："
#define TXT_PileWeight							"桩的水上重度(kN/m)："
#define TXT_PileUnderWaterWeight				"桩的水下重度(kN/m)："

#define TXT_Version								"版本：1.0.0.0"
#define TXT_DeveloperName						"苏东升"
#define TXT_Commpany							"中交水运规划设计院有限公司"
#define TXT_DevTime								"发布时间：2017/7/10"
#define TXT_Brief								"桩基承载力计算工具"
